---
label: Project
hide_body: false
fields:
- type: list
  name: tags
  label: tags
  config:
    min: 1
- type: text
  name: project_title
  label: Project Title
- type: text
  name: project_sub_head
  label: Project Sub-Head
- type: file
  name: featured_image
  label: Featured Image
  config:
    maxSize: 3
  description: Header image to display with post. Upload a picture with a minimum
    width of 1000px for best results
- type: text
  name: project_web_link
  label: Project Web Link
  description: A link to the project's website
- type: text
  name: project_repo_link
  label: Project Repo Link
  description: A link to the project's codebase
- type: list
  name: additional_images
  label: additional_images
- name: highlighted_project
  type: boolean
  label: Highlighted project
  description: Display this project on the website's homepage
